apiVersion: apps/v1
kind: Deployment
metadata:
  name: rv-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rv-catalog
  template:
    metadata:
      labels:
        app: rv-catalog
    spec:
      containers:
        - image: anzeha/rv-catalog
          name: rv-catalog
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://surus.db.elephantsql.com/pswumkxj
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: pswumkxj
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-pass
                  key: KUMULUZEE_DATASOURCES0_PASSWORD_RV
          ports:
            - containerPort: 8081
              name: server
              protocol: TCP
         

---

apiVersion: v1
kind: Service
metadata:
  name: rv-catalog
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: rv-catalog
